import 'package:flutter/material.dart';

const ColorScheme lightColorTheme = ColorScheme(
  primary: Color(0xFFFEFAF6),
  onPrimary: Colors.black,
  primaryContainer: Color(0xFFEADBC8),
  onPrimaryContainer: Colors.black,
  secondary: Color(0xFFEADBC8),
  onSecondary: Colors.black,
  secondaryContainer: Color(0xFF304C77),
  onSecondaryContainer: Colors.white,
  tertiary: Color(0xFFDAC0A3),
  onTertiary: Colors.black,
  error: Colors.redAccent,
  onError: Colors.white,
  background: Color(0xFFFEFAF6),
  onBackground: Colors.black,
  surface: Colors.white,
  onSurface: Colors.black,
  brightness: Brightness.light,
  inversePrimary: Color(0xFF121212),
);

const ColorScheme darkColorTheme = ColorScheme(
  primary: Color(0xFF222831),
  onPrimary: Colors.white,
  primaryContainer: Color(0xFFEADBC8),
  onPrimaryContainer: Colors.black,
  secondary: Color(0xFF1E1E1E),
  onSecondary: Colors.white,
  secondaryContainer: Color(0xFF304C77),
  onSecondaryContainer: Colors.white,
  tertiary: Color(0xFFDAC0A3),
  onTertiary: Colors.black,
  error: Colors.redAccent,
  onError: Colors.white,
  background: Color(0xFF222831),
  onBackground: Colors.white,
  surface: Color(0xFF1E1E1E),
  onSurface: Colors.white,
  brightness: Brightness.dark,
  inversePrimary: Color(0xFFFEFAF6),
);